/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import util.Datos;
/**
 *
 * @author Jostin Lima
 */
public class MantenimientoUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoUsuarios.class.getName());

    /**
     * Creates new form MantenimientoUsuarios
     */
    public MantenimientoUsuarios() {
        initComponents(); 
    setLocationRelativeTo(null); 
    // Forzamos la configuración de columnas antes de cargar
    configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnInactivar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUsuario = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtPassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtId = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mantenimiento de Usuarios");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 30));

        btnAgregar.setText("Add");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        btnModificar.setText("Modify");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        btnInactivar.setText("Inactivate");
        btnInactivar.addActionListener(this::btnInactivarActionPerformed);
        getContentPane().add(btnInactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        btnLimpiar.setText("Clean");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtUsuario.setPreferredSize(new java.awt.Dimension(170, 23));
        jScrollPane2.setViewportView(txtUsuario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblUsuarios);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 440, 130));

        txtPassword.setPreferredSize(new java.awt.Dimension(170, 23));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        txtId.setPreferredSize(new java.awt.Dimension(170, 23));
        jScrollPane1.setViewportView(txtId);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 305, -1, -1));

        btnRegresar.setText("Return");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        btnActivar.setText("Activate");
        btnActivar.addActionListener(this::btnActivarActionPerformed);
        getContentPane().add(btnActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 360));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String username = txtUsuario.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();

    // 1. Validar campos vacíos
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        return;
    }

    // 2. Validar si el usuario ya existe
    if (existeUsuario(username)) {
        JOptionPane.showMessageDialog(this, "El usuario ya existe.");
        return;
    }

    // 3. Generar ID y Agregar
    int nuevoId = Datos.listaUsuarios.isEmpty() ? 1 : Datos.listaUsuarios.get(Datos.listaUsuarios.size() - 1).getId() + 1;
    
    Datos.listaUsuarios.add(new Usuario(nuevoId, username, password, true, "user"));

    // 4. Finalizar
    JOptionPane.showMessageDialog(this, "Usuario #" + nuevoId + " agregado con éxito.");
    cargarTabla();   
    limpiarCampos();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         try {
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla.");
            return;
        }

        int idBusqueda = Integer.parseInt(txtId.getText()); 
        boolean encontrado = false;

        for (Usuario u : Datos.listaUsuarios) {
            if (u.getId() == idBusqueda) {
                u.setUsername(txtUsuario.getText());
                u.setPassword(new String(txtPassword.getPassword()));
                encontrado = true;
                break;
            }
        }

        if (encontrado) {
            JOptionPane.showMessageDialog(this, "Usuario actualizado.");
            cargarTabla();
            limpiarCampos();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error en el ID seleccionado.");
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnInactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarActionPerformed
        int fila = tblUsuarios.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla");
        return;
    }

    // Obtenemos el ID de la primera columna para estar seguros
    int id = (int) tblUsuarios.getValueAt(fila, 0);
    
    for (Usuario u : Datos.listaUsuarios) {
        if (u.getId() == id) {
            u.setEstado(false); // Cambia esto a setActivo si tu clase lo pide así
            break;
        }
    }

    JOptionPane.showMessageDialog(this, "Usuario inactivado");
    cargarTabla();
    }//GEN-LAST:event_btnInactivarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtId.setText("");
        txtUsuario.setText("");
    txtPassword.setText("");
    // Si tienes un ComboBox para el rol o un Checkbox para el estado:
    txtUsuario.requestFocus(); // Pone el cursor listo para escribir
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        int fila = tblUsuarios.getSelectedRow();
    
    // Obtenemos los datos de las columnas de la tabla
    Object valorId = tblUsuarios.getValueAt(fila, 0);
if (valorId != null) {
    txtId.setText(valorId.toString());
    txtUsuario.setText(tblUsuarios.getValueAt(fila, 1).toString());
    txtPassword.setText(tblUsuarios.getValueAt(fila, 2).toString());
}
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
         // 1. Creamos el cuadro de confirmación
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro que desea regresar al Menú Principal? Se perderán los datos no guardados.", 
            "Confirmar salida", 
            javax.swing.JOptionPane.YES_NO_OPTION, // Muestra botones Sí y No
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    // 2. Evaluamos la respuesta del Usuario
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        // Si responde SÍ, cerramos esta ventana
        this.dispose();     
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        int fila = tblUsuarios.getSelectedRow();

    // 1. Validar que seleccionaron a alguien en la tabla
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla para activarlo.");
        return;
    }

    // 2. Obtener el ID de la primera columna (columna 0)
    int id = (int) tblUsuarios.getValueAt(fila, 0);
    
    // 3. Buscar al usuario en la lista y cambiar su estado a true
    for (Usuario u : util.Datos.listaUsuarios) {
        if (u.getId() == id) {
            u.setEstado(true); // Aquí llamamos al método que arreglamos en el paso 1
            break;
        }
    }

    // 4. Actualizar la interfaz
    JOptionPane.showMessageDialog(this, "Usuario activado correctamente.");
    cargarTabla(); // Refresca la tabla para que diga "Activo"
    limpiarCampos(); // Limpia los cuadros de texto
    }//GEN-LAST:event_btnActivarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnInactivar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextPane txtId;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextPane txtUsuario;
    // End of variables declaration//GEN-END:variables


    private void cargarTabla() {
DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
    modelo.setRowCount(0); 

    for (Usuario u : Datos.listaUsuarios) {
        Object[] fila = new Object[5];
        fila[0] = u.getId();
        fila[1] = u.getUsername();
        fila[2] = u.getPassword();
        // Verifica si en tu clase Usuario es isEstado o isActivo
        fila[3] = u.isEstado() ? "Activo" : "Inactivo"; 
        fila[4] = u.getRol(); // Verifica si es getRol o getRole
        
        modelo.addRow(fila);
    }
}


private boolean existeUsuario(String user) {
     for (Usuario u : util.Datos.listaUsuarios) {
        if (u.getUsername().equalsIgnoreCase(user)) {
            return true; // Si lo encuentra, devuelve verdadero
        }
    }
    return false; // Si termina el ciclo y no lo vio, devuelve falso
}

    private void limpiarCampos() {
        // Borra el texto de cada campo
    txtId.setText("");
    txtUsuario.setText("");
    txtPassword.setText("");
    
    // Opcional: pone el foco en el campo de usuario para volver a escribir rápido
    txtUsuario.requestFocus();
    }

    private void configurarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
    String[] titulos = {"ID", "User", "Password", "State", "Role"};
    modelo.setColumnIdentifiers(titulos);
    cargarTabla();
    }


}
    
