/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import util.Datos;
import javax.swing.JOptionPane;
import modelo.Usuario;
/**
 *
 * @author Jostin Lima
 */
public class ReinicioClave extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReinicioClave.class.getName());

    /**
     * Creates new form ReinicioClave
     */
    public ReinicioClave() {
        initComponents();
    }
private boolean validarPassword(String pass) {
    if (pass.length() < 13) return false;

    boolean tieneMayus = false;
    boolean tieneEspecial = false;

    for (char c : pass.toCharArray()) {
        if (Character.isUpperCase(c)) {
            tieneMayus = true;
        }
        if (!Character.isLetterOrDigit(c)) {
            tieneEspecial = true;
        }
    }

    return tieneMayus && tieneEspecial;
}
private void limpiarCampos() {
    txtUsuario.setText("");
    txtNuevaPassword.setText("");
    txtConfirmarPassword.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUsuario = new javax.swing.JTextPane();
        txtNuevaPassword = new javax.swing.JPasswordField();
        txtConfirmarPassword = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reinicio de Clave");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtUsuario.setPreferredSize(new java.awt.Dimension(120, 23));
        jScrollPane1.setViewportView(txtUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        txtNuevaPassword.setPreferredSize(new java.awt.Dimension(120, 23));
        getContentPane().add(txtNuevaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        txtConfirmarPassword.setPreferredSize(new java.awt.Dimension(120, 23));
        getContentPane().add(txtConfirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btnGuardar.setText("Update");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        btnRegresar.setText("Return");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String usuario = txtUsuario.getText().trim();
    String nuevaPass = new String(txtNuevaPassword.getPassword());
    String confirmar = new String(txtConfirmarPassword.getPassword());

    // Validar vacíos
    if (usuario.isEmpty() || nuevaPass.isEmpty() || confirmar.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Campos vacíos");
        return;
    }

    // Validar coincidencia
    if (!nuevaPass.equals(confirmar)) {
        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
        return;
    }

    // Validar reglas de contraseña
    if (!validarPassword(nuevaPass)) {
        JOptionPane.showMessageDialog(this, 
            "La contraseña debe tener:\n- 13 caracteres\n- 1 mayúscula\n- 1 símbolo");
        return;
    }

    // Buscar Usuario
    Usuario encontrado = null;

    for (Usuario u : Datos.listaUsuarios) {
        if (u.getUsername().equals(usuario) && u.isActivo()) {
            encontrado = u;
            break;
        }
    }

    if (encontrado == null) {
        JOptionPane.showMessageDialog(this, "Usuario no encontrado o inactivo");
        return;
    }

    // Cambiar contraseña
    encontrado.setPassword(nuevaPass);

    JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente");

    limpiarCampos();// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // 1. Creamos el cuadro de confirmación
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro que desea regresar al Menú Principal? Se perderán los datos no guardados.", 
            "Confirmar salida", 
            javax.swing.JOptionPane.YES_NO_OPTION, // Muestra botones Sí y No
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    // 2. Evaluamos la respuesta del Usuario
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        // Si responde SÍ, cerramos esta ventana
        this.dispose(); 
        
        // Si tus ventanas son JFrames independientes, descomenta la línea de abajo:
        // new MenuPrincipal().setVisible(true);
    }
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReinicioClave().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtConfirmarPassword;
    private javax.swing.JPasswordField txtNuevaPassword;
    private javax.swing.JTextPane txtUsuario;
    // End of variables declaration//GEN-END:variables


}
